baseURL: https://my-website-zxy.netlify.app
languageCode: en-us
title: Xinyue Zhang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, I am Xinyue Zhang. Nice to meet you.
  blog: {}
  contact:
    address:
      - city: London, NW1 4SN
        country: United Kingdom
        street: Park Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: xzhang.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7415067576
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Xinyue Zhang
    enable: yes
    #quicklinks:
      #- alt: HTML5 UP
        #text: 'Design: '
        #url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      # label: Twitter
      # url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/xinyue_z/
      - icon: fa-github
        label: GitHub
        url: https://github.com/xinyuezhang23
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/xinyue-zhang-9942aa155/
  image: ''
  name: Your name
  navigation:
    # button1:
    #   - name: Get Started
    #     url: blogs
    # button2:
    #   - name: Log In
    #     url: '#'
    # links:
    #   - name: Home
    #     url: '#'
    #   - name: Blogs
    #     url: blogs
    #   - name: Generic Blog
    #     url: blogs/ipsum
    #   - name: Elements
    #     url: elements.html
    # menu: Menu
    subtitle: This is my website.
    title: LBS
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg # change yourself
        subtitle: Applied Statistic.
        title: Pre course assigment.
        url: blogs/xinyue #blogs/yourname
      - image: pic02.jpg
        subtitle: Making graphs
        title: Group assignment 1
        url: blogs/homework1
      - image: pic03.jpg
        subtitle: Internships and jobs
        title: Career
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  # two:
  #   buttonText: Get Started
  #   enable: yes
  #   subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
  #     \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
  #     condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
  #     pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
  #     Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
  #     amet pharetra et feugiat tempus."
  #   title: Massa libero
  #   url: blogs
