---
title: "Group assignment 2 of Applied Statics"
date: '2017-10-31T22:42:51-05:00'
description: About confidence intervals.
draft: no
image: mountain2.jpg
keywords: ''
slug: homework2
categories:
- ''
- ''
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>1. Climate change and temperature anomalies</h1>
<p>If we wanted to study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<p>To define temperature anomalies you need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.</p>
<p>We run the code below to load the file:</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p>Notice that, when using this function, we added two options: <code>skip</code> and <code>na</code>.</p>
<ol style="list-style-type: decimal">
<li>The <code>skip=1</code> option is there as the real data table only starts in Row 2, so we need to skip one row.</li>
<li><code>na = "***"</code> option informs R how missing observations in the spreadsheet are coded. When looking at the spreadsheet, you can see that missing data is coded as “***“. It is best to specify this here, as otherwise some of the data is not recognized as numeric data.</li>
</ol>
<p>Once the data is loaded, notice that there is a object titled <code>weather</code> in the <code>Environment</code> panel. If you cannot see the panel (usually on the top-right), go to <code>Tools</code> &gt; <code>Global Options</code> &gt; <code>Pane Layout</code> and tick the checkbox next to <code>Environment</code>. Click on the <code>weather</code> object, and the dataframe will pop up on a seperate tab. Inspect the dataframe.</p>
<p>For each month and year, the dataframe shows the deviation of temperature from the normal (expected). Further the dataframe is in wide format.</p>
<p>You have two objectives in this section:</p>
<ol style="list-style-type: decimal">
<li><p>Select the year and the twelve month variables from the <code>weather</code> dataset. We do not need the others (J-D, D-N, DJF, etc.) for this assignment. Hint: use <code>select()</code> function.</p></li>
<li><p>Convert the dataframe from wide to ‘long’ format. Hint: use <code>gather()</code> or <code>pivot_longer()</code> function. Name the new dataframe as <code>tidyweather</code>, name the variable containing the name of the month as <code>month</code>, and the temperature deviation values as <code>delta</code>.</p></li>
</ol>
<pre class="r"><code>#select desired columns
weather_cleaned&lt;-weather %&gt;% 
  select(1:13,)

#convert dataframe to long format
tidyweather&lt;- weather_cleaned %&gt;% 
  pivot_longer(cols=2:13,names_to = &quot;Month&quot;,values_to = &quot;delta&quot;)

tidyweather</code></pre>
<pre><code>## # A tibble: 1,704 x 3
##     Year Month delta
##    &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;
##  1  1880 Jan   -0.34
##  2  1880 Feb   -0.5 
##  3  1880 Mar   -0.22
##  4  1880 Apr   -0.29
##  5  1880 May   -0.05
##  6  1880 Jun   -0.15
##  7  1880 Jul   -0.17
##  8  1880 Aug   -0.25
##  9  1880 Sep   -0.22
## 10  1880 Oct   -0.31
## # ... with 1,694 more rows</code></pre>
<p>Inspecting our dataframe we find that it has three variables now, one each for</p>
<ol style="list-style-type: decimal">
<li>year,</li>
<li>month, and</li>
<li>delta, or temperature deviation.</li>
</ol>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trendline. To do that, we first need to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;
  )</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Is the effect of increasing temperature more pronounced in some months? We use <code>facet_wrap()</code> to produce a seperate scatter plot for each month, again with a smoothing line. Our chart now has human-readable labels; that is, each month is labeled “Jan”, “Feb”, “Mar” (full or abbreviated month names are fine), not <code>1</code>, <code>2</code>, <code>3</code>.</p>
<pre class="r"><code>#change labels so that month names appear instead of numbers
month_labs&lt;-c(&quot;Jan&quot;,&quot;Feb&quot;,&quot;Mar&quot;,&quot;Apr&quot;,&quot;May&quot;,&quot;Jun&quot;,&quot;Jul&quot;,&quot;Aug&quot;,&quot;Sep&quot;,&quot;Oct&quot;,&quot;Nov&quot;,&quot;Dec&quot;)
tidyweather$month &lt;-factor(tidyweather$month,label=month_labs,ordered = TRUE)

#plot the graph
ggplot(tidyweather,aes(x=Year,y=delta,color=month))+
  geom_point()+
  
  #facet by month
  facet_wrap(~month,
             scales = &quot;free&quot;)+
  theme(plot.title = element_text(hjust = 0.5,size=15,margin=margin(0,0,7,0)),strip.text = element_text(size=12))+
  geom_smooth(se=FALSE)+
  
  #add legends
    labs(title=&quot;Changes of Monthly Temperature Anomalies through years&quot;,
                             x=&quot;Year&quot;,
                             y=&quot;Delta Values&quot;,
                             color=&quot;Month&quot;)</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>It is sometimes useful to group data into different time periods to study historical data. For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time. NASA calcuialtes a temperature anomaly, as difference form the base periof of 1951-1980. The code below creates a new data frame called <code>comparison</code> that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<p>We remove data before 1800 and before using <code>filter</code>. Then, we use the <code>mutate</code> function to create a new variable <code>interval</code> which contains information on which period each observation belongs to. We can assign the different periods using <code>case_when()</code>.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Now that we have the <code>interval</code> variable, we can create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in. We are gonna set <code>fill</code> to <code>interval</code> to group and colour the data by different time periods.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with tranparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;,         #changing y-axis label to sentence case
    fill=&quot;Time Period&quot;,
    x= &quot;Delta&quot;
  )</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies. We can do this by using <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta=mean(delta,na.rm=TRUE)) 
average_annual_anomaly</code></pre>
<pre><code>## # A tibble: 142 x 2
##     Year annual_average_delta
##    &lt;dbl&gt;                &lt;dbl&gt;
##  1  1880               -0.276
##  2  1881               -0.167
##  3  1882               -0.208
##  4  1883               -0.281
##  5  1884               -0.425
##  6  1885               -0.432
##  7  1886               -0.432
##  8  1887               -0.436
##  9  1888               -0.238
## 10  1889               -0.178
## # ... with 132 more rows</code></pre>
<pre class="r"><code>#plotting the data:
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth(method = &quot;loess&quot;,se=FALSE) +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;,
    y     = &quot;Average Annual Delta&quot;
  )                         </code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>Our task is to construct a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the <code>infer</code> package. Recall that the dataframe <code>comparison</code> has already grouped temperature anomalies according to time intervals; we are only interested in what is happening between 2011-present.</p>
<pre class="r"><code>options(digits=3)
formula_ci &lt;- comparison %&gt;% 
  filter(interval==&quot;2011-present&quot;) %&gt;% 
  summarise(mean_delta=mean(delta,na.rm=TRUE),
            median_delta=median(delta,na.rm=TRUE),
            sd_delta=sd(delta,na.rm=TRUE),
            count=n(),
            t_critical=qt(0.975,count-1),
            se_delta=sd_delta/sqrt(count),
            lower_delta=mean_delta-t_critical*se_delta,
            upper_delta=mean_delta+t_critical*se_delta)
formula_ci</code></pre>
<pre><code>## # A tibble: 1 x 8
##   mean_delta median_delta sd_delta count t_critical se_delta lower_delta
##        &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;
## 1       1.06         1.04    0.274   132       1.98   0.0239        1.01
## # ... with 1 more variable: upper_delta &lt;dbl&gt;</code></pre>
<pre class="r"><code># use the infer package to construct a 95% CI for delta
set.seed(007)
library(infer)

bootstrap_delta&lt;- comparison %&gt;% 
  filter(interval==&quot;2011-present&quot;) %&gt;% 
  specify(response = delta) %&gt;% 
  generate(reps = 1000,type=&quot;bootstrap&quot;) %&gt;% 
  calculate(stat = &quot;mean&quot;)

bootstrap_delta</code></pre>
<pre><code>## Response: delta (numeric)
## # A tibble: 1,000 x 2
##    replicate  stat
##        &lt;int&gt; &lt;dbl&gt;
##  1         1  1.04
##  2         2  1.04
##  3         3  1.08
##  4         4  1.06
##  5         5  1.05
##  6         6  1.06
##  7         7  1.08
##  8         8  1.07
##  9         9  1.09
## 10        10  1.06
## # ... with 990 more rows</code></pre>
<pre class="r"><code>bootstrap_confidence_interval&lt;-bootstrap_delta %&gt;% 
  get_ci(level=0.95,type=&quot;percentile&quot;)
bootstrap_confidence_interval</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.01     1.11</code></pre>
<blockquote>
<p>What is the data showing us? let try to answer this question</p>
</blockquote>
<p>Essentially, we are trying to understand how the global warming starts from a minor issue and grows into a big problem. We use the variable called "delta" to describe temperature anomalies of every date (in our case, the first day of each month) and see how it changes through time. We could see from the first chart that the value of delta slowly climbed above 0 before rose sharply over 1 in a relatively shorter period of time. This demonstrates the fact that the global warming has severely exacerbated by human actions in last few years. Then we have a closer look on the picture of each month and could discover a similar pattern between months, they all experiencing a gradually increase before jumping remarkably with situation of first four months being the worst. Then we create a variable called “interval” to compare temperature anomalies between different time periods and we could also conclude from the density plot that things are getting worse because the average delta of these periods is increasing, some delta even reaching the level of 2. Finally, we only focus on the most recent period (2011-present) and calculate the confidence interval of the average delta, and the result ranges from 1.01 to 1.11, meaning that We are 95% confident that the average delta is between 1.01 and 1.11. In conclusion, having an average anomaly larger than 1 is never a good signal and we should treat this problem seriously and work togerther solving it.</p>
</div>
</div>
<div id="general-social-survey-gss" class="section level1">
<h1>2.General Social Survey (GSS)</h1>
<p>The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviours, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.</p>
<p>In this assignment we analyze data from the <strong>2016 GSS sample data</strong>, using it to estimate values of <em>population parameters</em> of interest about US adults. The GSS sample data file has 2867 observations of 935 variables, but we are only interested in very few of these variables and you are using a smaller file.</p>
<pre class="r"><code>gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;))</code></pre>
<p>You will also notice that many responses should not be taken into consideration, like “No Answer”, “Don’t Know”, “Not applicable”, “Refused to Answer”.</p>
<p>We will be creating 95% confidence intervals for population parameters. The variables we have are the following:</p>
<ul>
<li>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables. For example, if the response is 2.50 hours, this would be recorded as emailhr = 2 and emailmin = 30.</li>
<li><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media in 2016</li>
<li><code>sex</code>: Female - Male</li>
<li><code>degree</code>: highest education level attained</li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>Lets estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016:</p>
<ol style="list-style-type: decimal">
<li>We create a new variable, <code>snap_insta</code> that is <em>Yes</em> if the respondent reported using any of Snapchat (<code>snapchat</code>) or Instagram (<code>instagrm</code>), and <em>No</em> if not. If the recorded value was NA for both of these questions, the value in our new variable is also NA.</li>
</ol>
<pre class="r"><code>#Creating the variable snap_insta
gss_snap_insta &lt;-  gss %&gt;% 
  mutate(snap_insta = case_when(
    
    #Yes if either snapchat or instagram is Yes
    (snapchat == &quot;Yes&quot; | instagrm == &quot;Yes&quot;) ~ &quot;Yes&quot;,
    
    #NA if both snapchat and instagram are NA
    (snapchat == &quot;NA&quot; &amp; instagrm == &quot;NA&quot;) ~ &quot;NA&quot;,
    
    #No for all other cases
    TRUE ~ &quot;No&quot;
    ))</code></pre>
<ol style="list-style-type: decimal">
<li>Then we calculate the proportion of Yes’s for <code>snap_insta</code> among those who answered the question, i.e. excluding NAs.</li>
</ol>
<pre class="r"><code>gss_snap_insta %&gt;% 
  
  #Excluding NAs
  filter(snap_insta != &quot;NA&quot;) %&gt;% 
  group_by(snap_insta) %&gt;% 
  summarize(n = n()) %&gt;% 
  
  #Calculating proportion
  mutate(proportion_yes = n / sum(n)) %&gt;% 
  
  #Filtering values only for Yes
  filter(snap_insta == &#39;Yes&#39;)</code></pre>
<pre><code>## # A tibble: 1 x 3
##   snap_insta     n proportion_yes
##   &lt;chr&gt;      &lt;int&gt;          &lt;dbl&gt;
## 1 Yes          514          0.375</code></pre>
<ol style="list-style-type: decimal">
<li>Using the CI formula for proportions, we construct 95% CIs for men and women who used either Snapchat or Instagram</li>
</ol>
<pre class="r"><code>gss_snap_insta %&gt;% 
  
  #Excluding NAs
  filter(snap_insta != &quot;NA&quot;) %&gt;%
  group_by(sex, snap_insta) %&gt;%
  summarize(n = n()) %&gt;% 
  
  #Calculating proportion and CI for both genders
  mutate(proportion = n / sum(n),
         gender_count = sum(n),
         t_critical = qt(0.975, gender_count-1),
         se_proportion =  sqrt((proportion * (1-proportion)) / gender_count),
         margin_of_error = t_critical * se_proportion,
         CI_low = proportion - margin_of_error,
         CI_high = proportion + margin_of_error) %&gt;% 
  
  #Filtering values only for Yes
  filter(snap_insta == &#39;Yes&#39;)</code></pre>
<pre><code>## # A tibble: 2 x 10
## # Groups:   sex [2]
##   sex    snap_insta     n proportion gender_count t_critical se_proportion
##   &lt;chr&gt;  &lt;chr&gt;      &lt;int&gt;      &lt;dbl&gt;        &lt;int&gt;      &lt;dbl&gt;         &lt;dbl&gt;
## 1 Female Yes          322      0.419          769       1.96        0.0178
## 2 Male   Yes          192      0.318          603       1.96        0.0190
## # ... with 3 more variables: margin_of_error &lt;dbl&gt;, CI_low &lt;dbl&gt;, CI_high &lt;dbl&gt;</code></pre>
<p>The estimated population proportion of female Snapchat or Instagram users is 0.419 and the 95% confidence interval is [0.384, 0.454].
The estimated population proportion of male Snapchat or Instagram users is 0.318 and the 95% confidence interval is [0.281, 0.356].</p>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p>Can we estimate the <em>population</em> proportion of Twitter users by education level in 2016?.</p>
<p>There are 5 education levels in variable <code>degree</code> which, in ascending order of years of education, are Lt high school, High School, Junior college, Bachelor, Graduate.</p>
<ol style="list-style-type: decimal">
<li>Firstly we turn <code>degree</code> from a character variable into a factor variable. We sure the order is the correct one and that levels are not sorted alphabetically which is what R by default does.</li>
</ol>
<pre class="r"><code>#Converting degree to an ordered factor
gss_degree_factor &lt;- gss %&gt;% 
  mutate(degree = factor(degree, 
                         levels = c(&quot;Lt high school&quot;, &quot;High school&quot;, &quot;Junior college&quot;, &quot;Bachelor&quot;, &quot;Graduate&quot;), ordered = TRUE))

#Confirming if degree is an ordered factor
is.ordered(gss_degree_factor$degree)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<ol style="list-style-type: decimal">
<li>Afterwards we create a new variable, <code>bachelor_graduate</code> that is <em>Yes</em> if the respondent has either a <code>Bachelor</code> or <code>Graduate</code> degree. As before, if the recorded value for either was NA, the value in our new variable is also NA.</li>
</ol>
<pre class="r"><code>#Creating bachelor_graduate variable
gss_bachelor_graduate &lt;-  gss_degree_factor %&gt;% 
  
  mutate(bachelor_graduate = case_when(
                #Yes if either Bachelor or Graduate
                (degree == &#39;Bachelor&#39; | degree == &#39;Graduate&#39;) ~ &quot;Yes&quot;,
                #NA if degree is NA
                is.na(degree) ~ &quot;NA&quot;,
                #No for all other cases
                TRUE ~ &quot;No&quot;))</code></pre>
<ol style="list-style-type: decimal">
<li>Lets calculate the proportion of <code>bachelor_graduate</code> who do (Yes) and who don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>#Proportion of &#39;bachelor_graduate&#39; who use twitter
gss_bachelor_graduate %&gt;% 
  
  #Filtering bachelor_graduates and removing null values for twitter
  filter(bachelor_graduate == &quot;Yes&quot; &amp; twitter != &quot;NA&quot;) %&gt;% 
  
  group_by(twitter) %&gt;% 
  summarize(n = n()) %&gt;% 
  
  #Calculating proportion
  mutate(proportion = n / sum(n)) %&gt;% 

  #Arranging data in order of Yes and No
  arrange(factor(twitter, levels = c(&quot;Yes&quot;, &quot;No&quot;)))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   twitter     n proportion
##   &lt;chr&gt;   &lt;int&gt;      &lt;dbl&gt;
## 1 Yes       114      0.233
## 2 No        375      0.767</code></pre>
<ol style="list-style-type: decimal">
<li>Using the CI formula for proportions, we construct two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>gss_bachelor_graduate %&gt;% 
  
  #Filtering bachelor_graduates and removing null values for twitter
  filter(bachelor_graduate == &quot;Yes&quot; &amp; twitter != &quot;NA&quot;) %&gt;%
  
  group_by(twitter) %&gt;%
  summarize(n = n()) %&gt;% 
  
  #Calculating 2 confidence intervals
  mutate(proportion = n / sum(n),
         total_count = sum(n),
         t_critical = qt(0.975, total_count-1),
         se_proportion =  sqrt((proportion * (1-proportion)) / total_count),
         margin_of_error = t_critical * se_proportion,
         CI_low = proportion - margin_of_error,
         CI_high = proportion + margin_of_error) %&gt;%
  
  #Arranging data in order of Yes and No
  arrange(factor(twitter, levels = c(&quot;Yes&quot;, &quot;No&quot;)))</code></pre>
<pre><code>## # A tibble: 2 x 9
##   twitter     n proportion total_count t_critical se_proportion margin_of_error
##   &lt;chr&gt;   &lt;int&gt;      &lt;dbl&gt;       &lt;int&gt;      &lt;dbl&gt;         &lt;dbl&gt;           &lt;dbl&gt;
## 1 Yes       114      0.233         489       1.96        0.0191          0.0376
## 2 No        375      0.767         489       1.96        0.0191          0.0376
## # ... with 2 more variables: CI_low &lt;dbl&gt;, CI_high &lt;dbl&gt;</code></pre>
<ol style="list-style-type: decimal">
<li>Do these two Confidence Intervals overlap?</li>
</ol>
<p>The estimated population proportion of people who have either a Bachelor or Graduate degree and use Twitter is 0.233 and the 95% confidence interval is [0.196, 0.271].
The estimated population proportion of people who have either a Bachelor or Graduate degree and do not use Twitter is 0.767 and the 95% confidence interval is [0.729, 0.804].
These 2 confidence intervals do not overlap.</p>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Can we estimate the <em>population</em> parameter on time spent on email weekly?</p>
<ol style="list-style-type: decimal">
<li>We create a new variable called <code>email</code> that combines <code>emailhr</code> and <code>emailmin</code> to reports the number of minutes the respondents spend on email weekly.</li>
</ol>
<pre class="r"><code>gss_email &lt;- gss %&gt;%
  
  #Converting emailhr and emailmin to integers and calculating total mins
  mutate(emailhr = as.integer(emailhr),
         emailmin = as.integer(emailmin),
         email = (emailhr * 60) + (emailmin))</code></pre>
<ol style="list-style-type: decimal">
<li>it is helpful to visualise the distribution of this new variable.We find the mean and the median number of minutes respondents spend on email weekly.</li>
</ol>
<pre class="r"><code>#Plotting distribution of &#39;email&#39;
gss_email %&gt;%
  ggplot(aes(x=email)) + 
  geom_density() +
  
  #Adding title and axes labels
  labs(title = &quot;Distribution of the no. of minutes respondents spend on email weekly&quot;,
       x = &quot;Number of minutes the survey respondents spend on email weekly&quot;,
       y = &quot;Density&quot;
  ) +
  theme_bw()</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/email_distribution-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Calculating summary statistics for &#39;email&#39;
favstats(gss_email$email)</code></pre>
<pre><code>##  min Q1 median  Q3  max mean  sd    n missing
##    0 50    120 480 6000  417 680 1649    1218</code></pre>
<p>The distribution of the number of minutes the survey respondents spend on email weekly is heavily skewed towards the right. This means that most of the people responded with lower no. of minutes but some of the respondents spend much more time on email weekly. Therefore, the mean (417) of the variable is much greater than the median (120) of the variable, as the mean is pulled towards the right by the outliers.</p>
<p>Since the distribution is positively skewed with many outliers, median would be a better measure of central tendancy of the amount of time Americans spend on email weekly as median is not much affected by outliers as compared to mean.</p>
<ol style="list-style-type: decimal">
<li>Using the <code>infer</code> package, let’s calculate a 95% bootstrap confidence interval for the mean amount of time Americans spend on email weekly. We should interpret this interval in context of the data, reporting its endpoints in “humanized” units (e.g. instead of 108 minutes, report 1 hr and 8 minutes).</li>
</ol>
<pre class="r"><code>#Loading infer package
library(infer)

#Setting seed value
set.seed(1)

#Generate 1000 bootstrapped samples and calculating the mean
boot_mean_time &lt;- gss_email %&gt;% 
  #Filtering out NA values
  filter(!is.na(email)) %&gt;%
  
  specify(response = email) %&gt;% 
  
  generate(reps = 1000, type=&quot;bootstrap&quot;) %&gt;% 
  #Calculating mean for each sample
  calculate(stat = &#39;mean&#39;)

#Calculating CI for mean time spent on emails
bootstrap_ci &lt;- boot_mean_time %&gt;% 
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;) %&gt;% 
  
  #Rounding CIs to get integer value for total minutes
  mutate(lower_ci = round(lower_ci, 0),
         upper_ci = round(upper_ci, 0))

bootstrap_ci_time &lt;- bootstrap_ci %&gt;% 
  mutate(
    #Calculating hours and minutes from total number of minutes
    lower_ci_hour = lower_ci %/% 60,
    lower_ci_minutes = lower_ci %% 60,
    upper_ci_hour = upper_ci %/% 60,
    upper_ci_minutes = upper_ci %% 60
  )

bootstrap_ci_time</code></pre>
<pre><code>## # A tibble: 1 x 6
##   lower_ci upper_ci lower_ci_hour lower_ci_minutes upper_ci_hour
##      &lt;dbl&gt;    &lt;dbl&gt;         &lt;dbl&gt;            &lt;dbl&gt;         &lt;dbl&gt;
## 1      385      450             6               25             7
## # ... with 1 more variable: upper_ci_minutes &lt;dbl&gt;</code></pre>
<p>The 95% confidence interval for the mean amount of time Americans spend on email weekly is from 6 hours and 25 minutes to 7 hours and 30 minutes.
The population mean seems to be on the higher side because the sample data is heavily skewed towards the right. Due to this, the mean is pulled towards the outliers on the right side even though most of the data is towards the left side.</p>
<ol style="list-style-type: decimal">
<li>Would you expect a 99% confidence interval to be wider or narrower than the interval you calculated above? Explain your reasoning.</li>
</ol>
<p>Since the 99% confidence interval would be more confident than the 95% confidence interval, the 99% confidence interval would be wider as there is a 5% chance of being wrong in 95% confidence interval but there is just a 1% chance of being wrong in the 99% confidence interval.</p>
</div>
</div>
<div id="bidens-approval-margins" class="section level1">
<h1>3.Biden’s Approval Margins</h1>
<p>As we saw in class, fivethirtyeight.com has detailed data on <a href="https://projects.fivethirtyeight.com/biden-approval-ratings">all polls that track the president’s approval</a></p>
<pre class="r"><code># Import approval polls data directly off fivethirtyeight website
approval_polllist &lt;- read_csv(&#39;https://projects.fivethirtyeight.com/biden-approval-data/approval_polllist.csv&#39;) 

glimpse(approval_polllist)</code></pre>
<pre><code>## Rows: 1,598
## Columns: 22
## $ president           &lt;chr&gt; &quot;Joseph R. Biden Jr.&quot;, &quot;Joseph R. Biden Jr.&quot;, &quot;Jos~
## $ subgroup            &lt;chr&gt; &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;~
## $ modeldate           &lt;chr&gt; &quot;9/16/2021&quot;, &quot;9/16/2021&quot;, &quot;9/16/2021&quot;, &quot;9/16/2021&quot;~
## $ startdate           &lt;chr&gt; &quot;1/31/2021&quot;, &quot;1/31/2021&quot;, &quot;2/1/2021&quot;, &quot;2/1/2021&quot;, ~
## $ enddate             &lt;chr&gt; &quot;2/2/2021&quot;, &quot;2/2/2021&quot;, &quot;2/3/2021&quot;, &quot;2/3/2021&quot;, &quot;2~
## $ pollster            &lt;chr&gt; &quot;Rasmussen Reports/Pulse Opinion Research&quot;, &quot;YouGo~
## $ grade               &lt;chr&gt; &quot;B&quot;, &quot;B+&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;B&quot;, &quot;B&quot;, &quot;A-&quot;, &quot;B&quot;, &quot;B~
## $ samplesize          &lt;dbl&gt; 1500, 1500, 1500, 15000, 1005, 1500, 15000, 1429, ~
## $ population          &lt;chr&gt; &quot;lv&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;l~
## $ weight              &lt;dbl&gt; 0.3225, 1.0856, 0.3025, 0.2786, 0.8741, 0.2857, 0.~
## $ influence           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,~
## $ approve             &lt;dbl&gt; 51, 46, 52, 54, 57, 49, 54, 49, 54, 50, 54, 60, 51~
## $ disapprove          &lt;dbl&gt; 47, 38, 46, 33, 34, 48, 34, 39, 34, 47, 34, 32, 46~
## $ adjusted_approve    &lt;dbl&gt; 53.3, 47.3, 54.3, 52.5, 55.8, 51.3, 52.5, 49.7, 52~
## $ adjusted_disapprove &lt;dbl&gt; 41.0, 38.3, 40.0, 36.3, 35.1, 42.0, 37.3, 39.1, 37~
## $ multiversions       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA~
## $ tracking            &lt;lgl&gt; TRUE, NA, TRUE, TRUE, NA, TRUE, TRUE, NA, TRUE, TR~
## $ url                 &lt;chr&gt; &quot;https://www.rasmussenreports.com/public_content/p~
## $ poll_id             &lt;dbl&gt; 74333, 74332, 74338, 74366, 74345, 74347, 74367, 7~
## $ question_id         &lt;dbl&gt; 139595, 139593, 139642, 139733, 139652, 139654, 13~
## $ createddate         &lt;chr&gt; &quot;2/3/2021&quot;, &quot;2/3/2021&quot;, &quot;2/4/2021&quot;, &quot;2/11/2021&quot;, &quot;~
## $ timestamp           &lt;chr&gt; &quot;14:39:16 16 Sep 2021&quot;, &quot;14:39:16 16 Sep 2021&quot;, &quot;1~</code></pre>
<pre class="r"><code># Use `lubridate` to fix dates, as they are given as characters.

#load lubridate
library(lubridate)

#mutate date collumns to contain dates not characters
approval_polllist&lt;- approval_polllist %&gt;% 
  #use mdy() as dates are in US style date format
  mutate(modeldate = mdy(modeldate),
         startdate = mdy(startdate),
         enddate = mdy(enddate)
  )</code></pre>
<div id="create-a-plot" class="section level2">
<h2>Create a plot</h2>
<p>What I would like you to do is to calculate the average net approval rate (approve- disapprove) for each week since he got into office. I want you plot the net approval, along with its 95% confidence interval. There are various dates given for each poll, please use <code>enddate</code>, i.e., the date the poll ended.</p>
<pre class="r"><code>approval_polllist %&gt;% 
  #turn dates into weeks and calculate net approval rate in new column
  mutate(week = week(enddate),
         net_approval_rate = approve - disapprove) %&gt;% 
  
  #keep only &quot;All polls&quot; results
  filter(subgroup == &quot;All polls&quot;) %&gt;% 
  
  #remove unwanted entries and columns
  unique() %&gt;% 
  select(week, pollster, samplesize,net_approval_rate) %&gt;% 
  arrange(week) %&gt;% 
  
  #calculate average net approval rate for each week
  group_by(week) %&gt;% 
  summarise(mean_net_approval = mean(net_approval_rate),
            SD= sd(net_approval_rate),
            n=n(),
            SE=SD/sqrt(n),
  #since we don&#39;t know the population&#39;s σ we will use the t-distribution derived CIs
            t_critical=qt(0.975, n-1),
            upper_CI = mean_net_approval +t_critical*SE,
            lower_CI = mean_net_approval -t_critical*SE) %&gt;%

  #plot diagram using ggplot
  ggplot+
  geom_point(aes(x=week, y=mean_net_approval), color=&quot;red&quot;, alpha=0.4)+
  geom_line(aes(x=week, y=mean_net_approval),color=&quot;red&quot;, alpha=0.4)+
  
  #add regression line
  geom_smooth(aes(x=week, y=mean_net_approval),color=&quot;blue&quot;,se = FALSE)+
 
  #plot CIs
  geom_ribbon(aes(x= week,
                  ymin=mean_net_approval-t_critical*SE,
                  ymax=mean_net_approval+t_critical*SE), alpha=0.2)+
  
  #add reference line on y=0
   geom_hline(yintercept=0, lwd = 1.2,color = &quot;orange&quot;)+
  
  #add legends
  labs(title=&quot;Estimating Approval Margin (approve - disapprove) for Joe Biden&quot;,
       subtitle = &quot;Weekly Average of All Polls&quot;,
       x= &quot;Week of the Year&quot;,
       y= &quot;Average Net Approval&quot;)+
  
  #format y axis scale
  scale_y_continuous(
                    breaks = seq(-5, 30, by=5) ,
                    labels = function(x) paste0(x))+
  #change theme
   theme_bw()</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/approval%20rate%20plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Also, please add an orange line at zero. Your plot should look like this:</p>
<p><img src="D:/Rstudio_workspace/my_website/images/biden_approval_margin.png" width="100%" style="display: block; margin: auto;" />
Thanfully the grah we created is very similar to the target one (if not for slight changes in data)</p>
</div>
<div id="compare-confidence-intervals" class="section level2">
<h2>Compare Confidence Intervals</h2>
<p>Compare the confidence intervals for <code>week 3</code> and <code>week 25</code>. Can you explain what’s going on? One paragraph would be enough.</p>
<p>The difference is in the sample size available. While in week 3 we only had 4 polls to calculate the average from, in week 25 we had a record of 29 different polls to calculate the average. The bigger our sample size “n” is, (in this case the number of polls), the smaller the CIs are, given that they are calculated by subtracting and adding t_critical * s/<strong>qqrt(n)</strong> to the average value.</p>
<p><strong>Note</strong>
<em>when this analysis was first performed the data set included 4 polls from week 3. Since then those values have been removed from the data set, and weeks 3 is no longer included, resulting in the above diagram showing similar CIs across weeks. We can however note that week 4 (only 8 polls) has a significantly wider CI for the aforementioned reasons</em></p>
</div>
</div>
<div id="gapminder-revisited" class="section level1">
<h1>4.Gapminder revisited</h1>
<p>Recall the <code>gapminder</code> data frame from the gapminder package. That data frame contains just six columns from the larger <a href="https://www.gapminder.org/data/">data in Gapminder World</a>. In this part, you will join a few dataframes with more data than the ‘gapminder’ package. Specifically, you will look at data on</p>
<ul>
<li>Life expectancy at birth (life_expectancy_years.csv)</li>
<li>GDP per capita in constant 2010 US$ (<a href="https://data.worldbank.org/indicator/NY.GDP.PCAP.KD" class="uri">https://data.worldbank.org/indicator/NY.GDP.PCAP.KD</a>)</li>
<li>Female fertility: The number of babies per woman (<a href="https://data.worldbank.org/indicator/SP.DYN.TFRT.IN" class="uri">https://data.worldbank.org/indicator/SP.DYN.TFRT.IN</a>)</li>
<li>Primary school enrollment as % of children attending primary school (<a href="https://data.worldbank.org/indicator/SE.PRM.NENR" class="uri">https://data.worldbank.org/indicator/SE.PRM.NENR</a>)</li>
<li>Mortality rate, for under 5, per 1000 live births (<a href="https://data.worldbank.org/indicator/SH.DYN.MORT" class="uri">https://data.worldbank.org/indicator/SH.DYN.MORT</a>)</li>
<li>HIV prevalence (adults_with_hiv_percent_age_15_49.csv): The estimated number of people living with HIV per 100 population of age group 15-49.</li>
</ul>
<p>You must use the <code>wbstats</code> package to download data from the World Bank. The relevant World Bank indicators are <code>SP.DYN.TFRT.IN</code>, <code>SE.PRM.NENR</code>, <code>NY.GDP.PCAP.KD</code>, and <code>SH.DYN.MORT</code></p>
<pre class="r"><code># load gapminder HIV data
hiv &lt;- read_csv(here::here(&quot;data&quot;,&quot;adults_with_hiv_percent_age_15_49.csv&quot;))
life_expectancy &lt;- read_csv(here::here(&quot;data&quot;,&quot;life_expectancy_years.csv&quot;))

# get World bank data using wbstats
indicators &lt;- c(&quot;SP.DYN.TFRT.IN&quot;,&quot;SE.PRM.NENR&quot;, &quot;SH.DYN.MORT&quot;, &quot;NY.GDP.PCAP.KD&quot;)


library(wbstats)

worldbank_data &lt;- wb_data(country=&quot;countries_only&quot;, #countries only- no aggregates like Latin America, Europe, etc.
                          indicator = indicators, 
                          start_date = 1960, 
                          end_date = 2016)

# get a dataframe of information regarding countries, indicators, sources, regions, indicator topics, lending types, income levels,  from the World Bank API 
countries &lt;-  wbstats::wb_cachelist$countries</code></pre>
<p>You have to join the 3 dataframes (life_expectancy, worldbank_data, and HIV) into one. You may need to tidy your data first and then perform <a href="http://r4ds.had.co.nz/relational-data.html">join operations</a>. Think about what type makes the most sense <strong>and explain why you chose it</strong>.</p>
<pre class="r"><code>#tidy HIV
hiv_tidy&lt;-
  hiv %&gt;% 
  pivot_longer(cols=2:34, 
               names_to=&quot;year&quot;, 
               values_to = &quot;hiv_percent&quot;)
#view(hiv_tidy)

#tidy life expectancy
life_exp_tidy&lt;-
  # we only need date before 2021
  select( life_expectancy,c(1:223)) %&gt;% 
  pivot_longer(cols=2:223, 
               names_to=&quot;year&quot;, 
               values_to = &quot;life_exp&quot;)
#view(life_exp_tidy)

#join region to worldbank data by iso3c
worldbank_data&lt;- left_join(worldbank_data,select(countries, c(&#39;iso3c&#39;,&#39;region&#39;)))
# filter to see if there is missing values in region
worldbank_data %&gt;% 
  filter(is.na(region))</code></pre>
<pre><code>## # A tibble: 0 x 9
## # ... with 9 variables: iso2c &lt;chr&gt;, iso3c &lt;chr&gt;, country &lt;chr&gt;, date &lt;dbl&gt;,
## #   NY.GDP.PCAP.KD &lt;dbl&gt;, SE.PRM.NENR &lt;dbl&gt;, SH.DYN.MORT &lt;dbl&gt;,
## #   SP.DYN.TFRT.IN &lt;dbl&gt;, region &lt;chr&gt;</code></pre>
<p>To join the data frames, we use world bank data as the main one and left join others. Since each data frames contains some NA values in several years. If we use inner join, quite a lot rows will be missed.</p>
<pre class="r"><code># join life_expectancy, worldbank_data, and HIV
#worldbank_data contains year from 1960 to 2016
#rename date in worldbank data as year
worldbank_data &lt;- rename(worldbank_data,year = date )
worldbank_data$year &lt;- as.character(worldbank_data$year)
life_wb&lt;- 
  left_join(worldbank_data,life_exp_tidy,
             # by=c(&#39;country&#39;=&#39;country&#39;,&#39;year&#39;=&#39;year&#39;),
            copy= TRUE)


life_wb_hiv &lt;- 
  left_join (life_wb,hiv_tidy,
             # by = c(&#39;country&#39;=&#39;country&#39;,&#39;year&#39;=&#39;year&#39;),
             copy= TRUE)</code></pre>
<ol style="list-style-type: decimal">
<li>What is the relationship between HIV prevalence and life expectancy? Generate a scatterplot with a smoothing line to report your results. It is possible that we may find faceting useful</li>
</ol>
<pre class="r"><code>life_wb_hiv %&gt;% 
  #filter NA
  ggplot(aes(x=hiv_percent , y= life_exp))+
  geom_point(alpha=0.2)+
  geom_smooth( )+
  theme_bw()+
  ylim(40,100)+
  facet_wrap(~ region, scales = &quot;free&quot;  )+
  labs( x=&#39;HIV prevalence &#39;,
        y=&#39;Life expectancy&#39;)+
  NULL</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/hiv%20plots-1.png" width="648" style="display: block; margin: auto;" />
The higher HIV prevalence, the lower life expectancy. The have a slight negative correlation.</p>
<ol style="list-style-type: decimal">
<li>What is the relationship between fertility rate and GDP per capita? We will generate a scatter plot with a smoothing line to report your results. It is posible that we may find faceting by region useful</li>
</ol>
<pre class="r"><code>#Female fertility: SP.DYN.TFRT.IN
#GDP per capita: NY.GDP.PCAP.KD
life_wb_hiv %&gt;% 
  ggplot(aes(x=SP.DYN.TFRT.IN , y= NY.GDP.PCAP.KD))+
  geom_point(alpha=0.2)+
  scale_y_log10()+
  geom_smooth(method= &#39;lm&#39;)+
  facet_wrap(~ region  )+
  labs(
    x=&#39;Female fertility&#39;,
    y=&#39;GDP per capita&#39;
  )</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/fertility%20plots-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>  NULL</code></pre>
<pre><code>## NULL</code></pre>
<p>The lower and GDP per capita,the higher fertility rate. They have a negative correlation.</p>
<ol style="list-style-type: decimal">
<li>Which regions have the most observations with missing HIV data? Generate a bar chart (<code>geom_col()</code>), in descending order.</li>
</ol>
<pre class="r"><code>#join the region to hiv_tidy using countrycode

library(countrycode)
hiv_tidy$region   &lt;- countrycode(hiv_tidy$country, origin = &quot;country.name&quot;, destination = &quot;region&quot;)
hiv_tidy%&gt;% 
  filter(is.na(region))</code></pre>
<pre><code>## # A tibble: 0 x 4
## # ... with 4 variables: country &lt;chr&gt;, year &lt;chr&gt;, hiv_percent &lt;dbl&gt;,
## #   region &lt;chr&gt;</code></pre>
<pre class="r"><code>#count the missing values
hiv_na&lt;-hiv_tidy %&gt;% 
  filter(is.na(hiv_percent)) %&gt;% 
  group_by(region) %&gt;% 
  count(sort= TRUE)  
#plot
hiv_na %&gt;% 
  filter(!is.na(region)) %&gt;% 
  ggplot(aes(y=fct_reorder(region,n),x= n))+
  geom_col()+
  labs(
    x=&#39;Observations with missing HIV data&#39;,
    y=&#39;Region&#39;
  )+
  theme_bw()+
  NULL</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/regions-1.png" width="648" style="display: block; margin: auto;" />
Sub-Saharan Africa has the most observations with missing HIV data.</p>
<ol style="list-style-type: decimal">
<li>How has mortality rate for under 5 changed by region? In each region, let’s find the top 5 countries that have seen the greatest improvement, as well as those 5 countries where mortality rates have had the least improvement or even deterioration.</li>
</ol>
<pre class="r"><code># filter na value in mortality rate
mortality&lt;- worldbank_data %&gt;% 
  filter(!is.na(SH.DYN.MORT)) %&gt;% 
  select(country,year,region,SH.DYN.MORT)
#find the start/end year when the country has a mortality rate data
mortality_year&lt;-
  mortality%&gt;% 
  group_by(country) %&gt;% 
  summarise(min_year=min(year),max_year=max(year),region) %&gt;% 
  distinct

# calculate the improvement of each country
mortality_improvement&lt;-
  # find the mortality rate of start year.
  left_join(mortality_year,
            select(mortality,&#39;country&#39;,&#39;year&#39;,&#39;SH.DYN.MORT&#39;), 
            by = c(&#39;country&#39;=&#39;country&#39;,&#39;min_year&#39;=&#39;year&#39;)) %&gt;% 
  rename(mort_start=SH.DYN.MORT) %&gt;% 
  # find the mortality rate of end year.
  left_join(select(mortality,&#39;country&#39;,&#39;year&#39;,&#39;SH.DYN.MORT&#39;), 
            by = c(&#39;country&#39;=&#39;country&#39;,&#39;max_year&#39;=&#39;year&#39;)) %&gt;% 
  rename(mort_end=SH.DYN.MORT) %&gt;% 
  #calculate the improvement. We expect mortality rate becomes lower than before
  mutate(improvement_pct= (mort_start-mort_end)*100/mort_start) %&gt;%
  #we only need country,region and improvement data
  select(&#39;country&#39;,&#39;region&#39;,&#39;mort_start&#39;,&#39;mort_end&#39;,&#39;improvement_pct&#39;) %&gt;% 
  arrange(region,desc(improvement_pct))
glimpse(mortality_improvement)</code></pre>
<pre><code>## Rows: 193
## Columns: 5
## Groups: country [193]
## $ country         &lt;chr&gt; &quot;Korea, Rep.&quot;, &quot;Singapore&quot;, &quot;Japan&quot;, &quot;Thailand&quot;, &quot;Chin~
## $ region          &lt;chr&gt; &quot;East Asia &amp; Pacific&quot;, &quot;East Asia &amp; Pacific&quot;, &quot;East As~
## $ mort_start      &lt;dbl&gt; 112.2, 47.7, 39.7, 146.4, 117.6, 122.4, 92.6, 307.8, 1~
## $ mort_end        &lt;dbl&gt; 3.4, 2.7, 2.7, 10.3, 9.9, 10.8, 8.2, 30.1, 18.8, 21.6,~
## $ improvement_pct &lt;dbl&gt; 97.0, 94.3, 93.2, 93.0, 91.6, 91.2, 91.1, 90.2, 89.1, ~</code></pre>
<p>In mortality_improvement data frame, we can see mortality improvement over the past years is order by region and descending values.
Take East Asia &amp; Pacific region as an example. We can find that Korea,Rep ,Singapore ,Japan ,Thailand ,China have seen the greatest improvement. And Micronesia, Fed. Sts. ,Korea, Dem. People’s Rep.,Palau, Nauru,Tuvalu have seen the least improvement. There is no deterioration in all regions.</p>
<ol style="list-style-type: decimal">
<li>Is there a relationship between primary school enrollment and fertility rate?</li>
</ol>
<pre class="r"><code>life_wb_hiv %&gt;% 
  ggplot(aes(x= SP.DYN.TFRT.IN, y= SE.PRM.NENR))+
  geom_point(alpha=0.2)+
  geom_smooth(method=&#39;lm&#39;)+
  labs(
    x= &#39;Fertility rate in total bith per woman&#39;,
    y= &#39;Primary school enrollment (%)&#39;  )+
  theme_bw()+
  facet_wrap(~ region)+
  NULL</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/relationship-1.png" width="648" style="display: block; margin: auto;" />
Indedd there is a negative correlation. The higher fertility rate, the lower primary school enrollment rate.</p>
</div>
<div id="challenge-1-excess-rentals-in-tfl-bike-sharing" class="section level1">
<h1>Challenge 1: Excess rentals in TfL bike sharing</h1>
<p>Recall the TfL data on how many bikes were hired every single day. We can get the latest data by running the following</p>
<pre class="r"><code>url &lt;- &quot;https://data.london.gov.uk/download/number-bicycle-hires/ac29363e-e0cb-47cc-a97a-e216d900a6b0/tfl-daily-cycle-hires.xlsx&quot;

# Download TFL data to temporary file
httr::GET(url, write_disk(bike.temp &lt;- tempfile(fileext = &quot;.xlsx&quot;)))</code></pre>
<pre><code>## Response [https://airdrive-secure.s3-eu-west-1.amazonaws.com/london/dataset/number-bicycle-hires/2021-08-23T14%3A32%3A29/tfl-daily-cycle-hires.xlsx?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAJJDIMAIVZJDICKHA%2F20210916%2Feu-west-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20210916T223944Z&amp;X-Amz-Expires=300&amp;X-Amz-Signature=6727f1ca583e0cd0b0235a8d613e3e532663f78e849b7e38346069255c5bc9e3&amp;X-Amz-SignedHeaders=host]
##   Date: 2021-09-16 22:39
##   Status: 200
##   Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
##   Size: 173 kB
## &lt;ON DISK&gt;  C:\Users\Xinyue\AppData\Local\Temp\Rtmp8c2GNi\file6b80142bc0.xlsx</code></pre>
<pre class="r"><code># Use read_excel to read it as dataframe
bike0 &lt;- read_excel(bike.temp,
                   sheet = &quot;Data&quot;,
                   range = cell_cols(&quot;A:B&quot;))

# change dates to get year, month, and week
bike &lt;- bike0 %&gt;% 
  clean_names() %&gt;% 
  rename (bikes_hired = number_of_bicycle_hires) %&gt;% 
  mutate (year = year(day),
          month = lubridate::month(day, label = TRUE),
          week = isoweek(day))</code></pre>
<p>We can easily create a facet grid that plots bikes hired by month and year.</p>
<p><img src="D:/Rstudio_workspace/my_website/images/tfl_distributions_monthly.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Look at May and Jun and compare 2020 with the previous years. What’s happening?
The effect of the pandemic is clear. Bike rentals seem to fall considerably mainly because of lockdown</p>
<p>We will then try to replicate the graphs:
For both of these graphs, we have to calculate the expected number of rentals per week or month between 2016-2019 and then, see how each week/month of 2020-2021 compares to the expected rentals. Think of the calculation <code>excess_rentals = actual_rentals - expected_rentals</code>.</p>
<p>Should you use the mean or the median to calculate your expected rentals? Why?</p>
<pre class="r"><code>#find key statistics about 2016-2019 period
bike_new&lt;-bike %&gt;% 
  filter(year %in% c(2016,2017,2018,2019))
favstats(bikes_hired~month,data=bike_new)</code></pre>
<pre><code>##    month   min    Q1 median    Q3   max  mean   sd   n missing
## 1    Jan  4894 16515  22430 25484 38042 20617 6106 124       0
## 2    Feb  8975 18624  23738 25791 35420 22049 5843 113       0
## 3    Mar  6362 19662  24782 28083 35321 23237 6982 124       0
## 4    Apr  7998 23946  28475 33427 45048 28299 7042 120       0
## 5    May 16227 28948  34613 38064 45435 33270 6467 124       0
## 6    Jun 13358 31250  37171 39900 46084 35413 6194 120       0
## 7    Jul 16392 34586  39332 42477 46625 38109 5996 124       0
## 8    Aug  8177 30762  35318 39350 44648 34393 6462 124       0
## 9    Sep 12376 29539  34736 36852 44909 33013 5996 120       0
## 10   Oct 10043 27085  32399 34717 39569 30235 6337 124       0
## 11   Nov  9585 19163  26730 29085 34747 24752 6145 120       0
## 12   Dec  5143 12885  18889 25199 37401 19118 7482 124       0</code></pre>
<pre class="r"><code>#find average monthly rentals for 2016-2019
monthly_avg &lt;- bike %&gt;% 
  filter(year %in% c(2016,2017,2018,2019)) %&gt;% 
  group_by(month) %&gt;% 
  summarise(
    mean_bikes_overall = mean(bikes_hired)
  )
monthly_avg</code></pre>
<pre><code>## # A tibble: 12 x 2
##    month mean_bikes_overall
##    &lt;ord&gt;              &lt;dbl&gt;
##  1 Jan               20617.
##  2 Feb               22049.
##  3 Mar               23237.
##  4 Apr               28299.
##  5 May               33270.
##  6 Jun               35413.
##  7 Jul               38109.
##  8 Aug               34393.
##  9 Sep               33013.
## 10 Oct               30235.
## 11 Nov               24752.
## 12 Dec               19118.</code></pre>
<pre class="r"><code>#find average monthly rentals for 2016-2019 (each year seperate)
bikes_monthly_mean &lt;- bike %&gt;% 
  filter(year %in% c(2016,2017,2018,2019,2020,2021)) %&gt;% 
  group_by(month, year) %&gt;% 
  summarize(
    mean_monthly_bikes = mean(bikes_hired)
  )
bikes_monthly_mean</code></pre>
<pre><code>## # A tibble: 67 x 3
## # Groups:   month [12]
##    month  year mean_monthly_bikes
##    &lt;ord&gt; &lt;dbl&gt;              &lt;dbl&gt;
##  1 Jan    2016             18914.
##  2 Jan    2017             20596.
##  3 Jan    2018             20836.
##  4 Jan    2019             22123.
##  5 Jan    2020             22893.
##  6 Jan    2021             13218.
##  7 Feb    2016             20608.
##  8 Feb    2017             22091.
##  9 Feb    2018             20587.
## 10 Feb    2019             24961.
## # ... with 57 more rows</code></pre>
<pre class="r"><code>bikes_with_avg &lt;- left_join(bikes_monthly_mean, monthly_avg, on=&#39;month&#39;)

#find change in rentals compared to average
bikes_with_avg &lt;- bikes_with_avg %&gt;% 
  mutate(excess_rentals = mean_monthly_bikes - mean_bikes_overall)

bikes_with_avg</code></pre>
<pre><code>## # A tibble: 67 x 5
## # Groups:   month [12]
##    month  year mean_monthly_bikes mean_bikes_overall excess_rentals
##    &lt;ord&gt; &lt;dbl&gt;              &lt;dbl&gt;              &lt;dbl&gt;          &lt;dbl&gt;
##  1 Jan    2016             18914.             20617.        -1703. 
##  2 Jan    2017             20596.             20617.          -20.6
##  3 Jan    2018             20836.             20617.          218. 
##  4 Jan    2019             22123.             20617.         1505. 
##  5 Jan    2020             22893.             20617.         2276. 
##  6 Jan    2021             13218.             20617.        -7399. 
##  7 Feb    2016             20608.             22049.        -1441. 
##  8 Feb    2017             22091.             22049.           42.1
##  9 Feb    2018             20587.             22049.        -1462. 
## 10 Feb    2019             24961.             22049.         2912. 
## # ... with 57 more rows</code></pre>
<pre class="r"><code>month_labs&lt;-c(&quot;Jan&quot;,&quot;Feb&quot;,&quot;Mar&quot;,&quot;Apr&quot;,&quot;May&quot;,&quot;Jun&quot;,&quot;Jul&quot;,&quot;Aug&quot;,&quot;Sep&quot;,&quot;Oct&quot;,&quot;Nov&quot;,&quot;Dec&quot;)
bikes_with_avg$month &lt;-factor(bikes_with_avg$month,label=month_labs,ordered = TRUE)
bikes_with_avg</code></pre>
<pre><code>## # A tibble: 67 x 5
## # Groups:   month [12]
##    month  year mean_monthly_bikes mean_bikes_overall excess_rentals
##    &lt;ord&gt; &lt;dbl&gt;              &lt;dbl&gt;              &lt;dbl&gt;          &lt;dbl&gt;
##  1 Jan    2016             18914.             20617.        -1703. 
##  2 Jan    2017             20596.             20617.          -20.6
##  3 Jan    2018             20836.             20617.          218. 
##  4 Jan    2019             22123.             20617.         1505. 
##  5 Jan    2020             22893.             20617.         2276. 
##  6 Jan    2021             13218.             20617.        -7399. 
##  7 Feb    2016             20608.             22049.        -1441. 
##  8 Feb    2017             22091.             22049.           42.1
##  9 Feb    2018             20587.             22049.        -1462. 
## 10 Feb    2019             24961.             22049.         2912. 
## # ... with 57 more rows</code></pre>
<pre class="r"><code>#create first required plot

#create variables &quot;up&quot; and &quot;down&quot; denoting the shifts from the average
bikes_with_avg_new&lt;-bikes_with_avg %&gt;% 
  mutate(up=ifelse(excess_rentals&gt;0,as.numeric(excess_rentals),0),down=ifelse(excess_rentals&lt;0,as.numeric(excess_rentals),0)) %&gt;% 
  arrange(year,month)

bikes_with_avg_new</code></pre>
<pre><code>## # A tibble: 67 x 7
## # Groups:   month [12]
##    month  year mean_monthly_bikes mean_bikes_overall excess_rentals    up   down
##    &lt;ord&gt; &lt;dbl&gt;              &lt;dbl&gt;              &lt;dbl&gt;          &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1 Jan    2016             18914.             20617.         -1703.    0  -1703.
##  2 Feb    2016             20608.             22049.         -1441.    0  -1441.
##  3 Mar    2016             21435              23237.         -1802.    0  -1802.
##  4 Apr    2016             25444.             28299.         -2856.    0  -2856.
##  5 May    2016             32699.             33270.          -571.    0   -571.
##  6 Jun    2016             32108.             35413.         -3306.    0  -3306.
##  7 Jul    2016             38336.             38109.           227.  227.     0 
##  8 Aug    2016             37368.             34393.          2975. 2975.     0 
##  9 Sep    2016             35101.             33013.          2088. 2088.     0 
## 10 Oct    2016             30488.             30235.           254.  254.     0 
## # ... with 57 more rows</code></pre>
<pre class="r"><code>#plot diagram
ggplot(bikes_with_avg_new, aes(x = month)) +
  geom_line(aes(group=1, y = mean_bikes_overall),color = &quot;blue&quot;) +
  geom_line(aes(group=1, y = mean_monthly_bikes),color=&quot;black&quot;,alpha=0.6)+
  
  #include lines that show shifts from mean
  geom_ribbon(aes(group=1, ymin = mean_bikes_overall, ymax = mean_bikes_overall+up),fill=&quot;#7DCD85&quot;,alpha=0.4)+
  geom_ribbon(aes(group=1, ymin = mean_bikes_overall, ymax = mean_bikes_overall+down),fill=&quot;#CB454A&quot;,alpha=0.4)+
  
  #facet wrap by year
  facet_wrap(~year) +
  
  #change theme and legends
  theme_bw()+labs(
    title = &quot;Monthly changes in TfL bike rentals&quot;,
    subtitle = &quot;Change from monthly average shown in blue\nand calculated between 2016-2019 &quot;,
    y=&quot;Bike rentals&quot;,
    x=&quot;&quot;,
    caption = &quot;Source:Tfl, London Data Store&quot;
    
  )</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/first%20graph-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#create dataframes for second required graph

#change certain dates (some days of the week at the end or the start of the year are counted towards the wrong year)
bike1&lt;-bike %&gt;% 
  mutate(month=as.numeric(month)) %&gt;% 
  mutate(year=ifelse(month==12 &amp; week==1, year+1,year)) %&gt;% 
  mutate(year=ifelse(month==1 &amp; week==53, year-1,year))

#calculate weekly averages
weekly_avg &lt;- bike1 %&gt;% 
  filter(year %in% c(2016,2017,2018,2019)) %&gt;% 
  group_by(week) %&gt;% 
  summarise(
    mean_weekly_overall = mean(bikes_hired)
  )

weekly_avg</code></pre>
<pre><code>## # A tibble: 52 x 2
##     week mean_weekly_overall
##    &lt;dbl&gt;               &lt;dbl&gt;
##  1     1              17388.
##  2     2              22056.
##  3     3              21892.
##  4     4              21470.
##  5     5              21194.
##  6     6              20226.
##  7     7              23254.
##  8     8              23575.
##  9     9              20167 
## 10    10              23403.
## # ... with 42 more rows</code></pre>
<pre class="r"><code>#edit for week 53(some days are counted towards the wrong year)
weekly_avg_53 &lt;- bike1 %&gt;% 
  filter(year == 2015 &amp; week==53) %&gt;% 
  group_by(week) %&gt;% 
  summarise(
    mean_weekly_overall = mean(bikes_hired)
  )

#combine the dataframes to create final dataframe
weekly_avg_new&lt;-full_join(weekly_avg,weekly_avg_53,on=&#39;week&#39;)
weekly_avg_new</code></pre>
<pre><code>## # A tibble: 53 x 2
##     week mean_weekly_overall
##    &lt;dbl&gt;               &lt;dbl&gt;
##  1     1              17388.
##  2     2              22056.
##  3     3              21892.
##  4     4              21470.
##  5     5              21194.
##  6     6              20226.
##  7     7              23254.
##  8     8              23575.
##  9     9              20167 
## 10    10              23403.
## # ... with 43 more rows</code></pre>
<pre class="r"><code>bikes_weekly_mean &lt;- bike1 %&gt;%
  filter(year %in% c(2016,2017,2018,2019,2020,2021)) %&gt;%
  group_by(year,week) %&gt;%
  summarize(
    mean_weekly_bikes = mean(bikes_hired)
  )

bikes_weekly_mean</code></pre>
<pre><code>## # A tibble: 291 x 3
## # Groups:   year [6]
##     year  week mean_weekly_bikes
##    &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt;
##  1  2016     1            18867.
##  2  2016     2            20255.
##  3  2016     3            20937.
##  4  2016     4            20550.
##  5  2016     5            21230 
##  6  2016     6            19896.
##  7  2016     7            19655.
##  8  2016     8            21205.
##  9  2016     9            19865.
## 10  2016    10            21974.
## # ... with 281 more rows</code></pre>
<pre class="r"><code>bikes_week_avg &lt;- left_join(bikes_weekly_mean, weekly_avg_new, on=&#39;week&#39;)

bikes_week_avg &lt;- bikes_week_avg %&gt;% 
  mutate(excess_weekly_rentals = mean_weekly_bikes - mean_weekly_overall)

#mutate to include &quot;up&quot; and &quot;down&quot; variables (similarly as above)
bikes_week_avg_new&lt;-bikes_week_avg %&gt;%
  mutate(excess_weekly_rentals_percent=(excess_weekly_rentals/mean_weekly_overall)*100,
         up=ifelse(excess_weekly_rentals&gt;0,
                   as.numeric(excess_weekly_rentals/mean_weekly_overall)*100,
                   0),
         down=ifelse(excess_weekly_rentals&lt;0,
                     as.numeric(excess_weekly_rentals/mean_weekly_overall)*100
                     ,0)
         ) %&gt;%
  arrange(year,week)

bikes_week_avg_new</code></pre>
<pre><code>## # A tibble: 291 x 8
## # Groups:   year [6]
##     year  week mean_weekly_bikes mean_weekly_overall excess_weekly_rentals
##    &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt;               &lt;dbl&gt;                 &lt;dbl&gt;
##  1  2016     1            18867.              17388.                1479. 
##  2  2016     2            20255.              22056.               -1802. 
##  3  2016     3            20937.              21892.                -955. 
##  4  2016     4            20550.              21470.                -920. 
##  5  2016     5            21230               21194.                  35.8
##  6  2016     6            19896.              20226.                -330. 
##  7  2016     7            19655.              23254.               -3599  
##  8  2016     8            21205.              23575.               -2370. 
##  9  2016     9            19865.              20167                 -302. 
## 10  2016    10            21974.              23403.               -1429. 
## # ... with 281 more rows, and 3 more variables:
## #   excess_weekly_rentals_percent &lt;dbl&gt;, up &lt;dbl&gt;, down &lt;dbl&gt;</code></pre>
<pre class="r"><code>#plot second graph
ggplot(bikes_week_avg_new, aes(x = week)) +
  geom_line(aes(group=1, y = excess_weekly_rentals_percent),color=&quot;black&quot;,alpha=0.3) +

  #include areas denoting shifts from the average
  geom_ribbon(aes(group=1, ymin = 0, ymax = up),fill=&quot;#7DCD85&quot;,alpha=0.4)+
  geom_ribbon(aes(group=1, ymin = 0, ymax = down),fill=&quot;#CB454A&quot;,alpha=0.4)+
  
  #facet wrap by year
  facet_wrap(~year) +
  
  #edit scales
  scale_y_continuous(breaks = c(-50, 0, 50,100),
                     labels = function(x) paste0(x, &quot;%&quot;),limits = c(-50,100))+
  scale_x_continuous(breaks = seq(0,53,by=13),
                    limits = c(1,53))+
  
  #edit legends theme and appearance of graph
  theme_bw()+
  annotate(&quot;rect&quot;, xmin=14, xmax=26, ymin=-Inf, ymax=Inf, alpha=0.4, fill=&quot;grey&quot;)+
  annotate(&quot;rect&quot;, xmin=40, xmax=52, ymin=-Inf, ymax=Inf, alpha=0.4, fill=&quot;grey&quot;)+
  
  #include lines at axis
  geom_rug(data=bikes_week_avg_new[bikes_week_avg_new$up&gt;0,],sides=&quot;b&quot;,colour=&quot;#7DCD85&quot;)+
  geom_rug(data=bikes_week_avg_new[bikes_week_avg_new$down&lt;0,],sides=&quot;b&quot;,colour=&quot;#CB454A&quot;)+
  
  #change legends
  labs(
    title = &quot;Weekly changes in TfL bike rentals&quot;,
    subtitle = &quot;% Change from weekly averages\ncalculated between 2016-2019 &quot;,
    y=&quot;&quot;,
    x=&quot;week&quot;,
    caption = &quot;Source:Tfl, London Data Store&quot;

  )</code></pre>
<p><img src="/blogs/homework2_SG4_files/figure-html/plot%20second%20graph-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: Xenia Huber, Wei Guo, Harsh Tripathi,Xinyue Zhang, Nikolaos Panayotou</li>
<li>Approximately how much time did you spend on this problem set: 10 hours</li>
<li>What, if anything, gave you the most trouble: No problems</li>
</ul>
</div>
<div id="rubric" class="section level1">
<h1>Rubric</h1>
<p>Check minus (1/5): Displays minimal effort. Doesn’t complete all components. Code is poorly written and not documented. Uses the same type of plot for each graph, or doesn’t use plots appropriate for the variables being analyzed.</p>
<p>Check (3/5): Solid effort. Hits all the elements. No clear mistakes. Easy to follow (both the code and the output).</p>
<p>Check plus (5/5): Finished all components of the assignment correctly and addressed both challenges. Code is well-documented (both self-documented and with additional comments as necessary). Used tidyverse, instead of base R. Graphs and tables are properly labelled. Analysis is clear and easy to follow, either because graphs are labeled clearly or you’ve written additional text to describe how you interpret the output.</p>
</div>
